Updates

diff --git a/alias b/alias
--- a/alias
+++ b/alias
@@ -18,11 +18,11 @@ alias lta="lt -a"
 alias lx="eza -lbhHigUmuSa@ --time-style=long-iso --git --color-scale" # eza --long --binary --header --links --inode --group --created --modified --accessed --blocksize --all --extended --time-style...
 
 # Not used
-alias lS="eza --icons -1" # eza --icons --oneline
-alias ll="eza -lbGF --git" # eza --long --binary --grid --classify --git
+alias lS="eza --icons -1"                   # eza --icons --oneline
+alias ll="eza -lbGF --git"                  # eza --long --binary --grid --classify --git
 alias llm="eza -lbGd --git --sort=modified" # eza --long --binary --grid --list-dirs
 
-alias cat="bat --plain"
+alias cat="bat --style=plain --paging=never"
 
 alias rmnm="find . -name "node_modules" -type d -prune -exec rm -rf '{}' +"
 alias wstorml='wstorm -e'
@@ -35,53 +35,54 @@ alias lzd="lazydocker"
 
 # https://github.com/junegunn/fzf/wiki/examples#changing-directory
 fcd() {
-    local dir
-    dir=$(find ${1:-.} -path '*/\.*' -prune -o -type d -print \
-            -maxdepth 2 2> /dev/null | \
-            fzf +m \
-            --preview 'eza --tree --level=2 --icons --color=always {} | head -200' \
-            --bind 'ctrl-d:preview-half-page-down,ctrl-u:preview-half-page-up,ctrl-f:preview-page-down,ctrl-b:preview-page-up' \
-        )
-    cd "$dir"
+	local dir
+	dir=$(
+		find "${1:-.}" -path '*/\.*' -prune -o -type d -print \
+			-maxdepth 2 2>/dev/null |
+			fzf +m \
+				--preview 'eza --tree --level=2 --icons --color=always {} | head -200' \
+				--bind 'ctrl-d:preview-half-page-down,ctrl-u:preview-half-page-up,ctrl-f:preview-page-down,ctrl-b:preview-page-up'
+	)
+	cd "$dir" || exit
 }
 
 ccd() {
-  local dir
-  dir=$(\
-        find \
-            ~/Code \
-            ~/Dotfiles \
-            ~ \
-            -mindepth 1 -maxdepth 1 -type d | \
-            fzf \
-                --preview 'eza --tree --level=1 --icons --color=always {} | head -200' \
-                --bind 'ctrl-d:preview-half-page-down,ctrl-u:preview-half-page-up,ctrl-f:preview-page-down,ctrl-b:preview-page-up' \
-        )
-  cd "$dir"
+	local dir
+	dir=$(
+		find \
+			~/Code \
+			~/Dotfiles \
+			~ \
+			-mindepth 1 -maxdepth 1 -type d |
+			fzf \
+				--preview 'eza --tree --level=1 --icons --color=always {} | head -200' \
+				--bind 'ctrl-d:preview-half-page-down,ctrl-u:preview-half-page-up,ctrl-f:preview-page-down,ctrl-b:preview-page-up'
+	)
+	cd "$dir" || exit
 }
 
 export-vars() {
-  if [ -f "$1" ]; then
-    while IFS='=' read -r key value; do
-      # Skip empty lines or lines where the key is empty
-      if [ -n "$key" ] && [ -n "$value" ]; then
-        export "$key=$value"
-      fi
-    done < "$1"
-  else
-    echo "File not found: $1"
-  fi
+	if [ -f "$1" ]; then
+		while IFS='=' read -r key value; do
+			# Skip empty lines or lines where the key is empty
+			if [ -n "$key" ] && [ -n "$value" ]; then
+				export "$key=$value"
+			fi
+		done <"$1"
+	else
+		echo "File not found: $1"
+	fi
 }
 
 goWork() {
-    cp ~/.npm_work_rc ~/.npmrc
-    cp ~/.ssh_config_work ~/.ssh/config
-    ssh-add -d ~/.ssh/id_ed25519_personal
+	cp ~/.npm_work_rc ~/.npmrc
+	cp ~/.ssh_config_work ~/.ssh/config
+	ssh-add -d ~/.ssh/id_ed25519_personal
 }
 
 goPersonal() {
-    cp ~/.npm_personal_rc ~/.npmrc
-    cp ~/.ssh_config_personal ~/.ssh/config
-    ssh-add ~/.ssh/id_ed25519_personal
+	cp ~/.npm_personal_rc ~/.npmrc
+	cp ~/.ssh_config_personal ~/.ssh/config
+	ssh-add ~/.ssh/id_ed25519_personal
 }
 
